name: CI

on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    env:
      ATTIC_ENDPOINT: ${{ secrets.ATTIC_ENDPOINT }}
      ATTIC_TOKEN_PUBLIC: ${{ secrets.ATTIC_TOKEN_PUBLIC }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Attic cache
        if: ${{ env.ATTIC_ENDPOINT != '' && env.ATTIC_TOKEN_PUBLIC != '' }}
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ env.ATTIC_ENDPOINT }}
          cache: public
          token: ${{ env.ATTIC_TOKEN_PUBLIC }}
          skip-push: ${{ github.event_name == 'pull_request' }}

      - name: Build module
        run: nix build -L

      - name: Run tests
        run: nix build .#unit-tests -L
